spring:
  profiles:
    active: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://sedev-db.c3c8rw5jgufd.ap-southeast-2.rds.amazonaws.com/SE_DEV?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    hikari:
      username: admin
      password: ol10220502
      auto-commit: false  # AOP로 트랜잭션을 제어하기 때문에 false로 사용 (default: true)
      maximum-pool-size: 30  # pool에 유지시킬 수 있는 최대 커넥션 수
      connection-timeout: 30000 # 커넥션 타임 아웃 (30s)
      max-lifetime: 1800000  # pool 에서 미사용 커넥션 최대 수명 시간 (30m)
      leak-detection-threshold: 2000 # 커넥션이 누수 로그메세지 나오기전 커넥션을 검사하여 pool에서 커넥션을 내보낼 수 있는 시간
      idle-timeout: 60000 # pool 미사용 커넥션 유지 시간 (10m)
      minimum-idle: 1  # 최소 커넥션 유지 개수 (default: same as maximumPoolSize)
        
mybatis:
  enabled: true
  config-location: classpath:/sql/configuration.xml
  mapper-locations: classpath:/sql/mysql/**/sql-*.xml

server:
  port: 8080